### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by tangligen1995** [WaxMoon/MultiAppDemo#2]
runtime.cc:655]   native: #111 pc 0000000000366eac  /apex/com.android.art/lib64/libart.so (art::(anonymous namespace)::CheckJNI::CallBooleanMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+72)
    runtime.cc:655]   native: #112 pc 000000000009e698  /system/lib64/libandroid_runtime.so (_JNIEnv::CallBooleanMethod(_jobject*, _jmethodID*, ...)+124)
    runtime.cc:655]   native: #113 pc 0000000000127228  /system/lib64/libandroid_runtime.so (JavaBBinder::onTransact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+156)
    runtime.cc:655]   native: #114 pc 000000000004c82c  /system/lib64/libbinder.so (android::BBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+232)
    runtime.cc:655]   native: #115 pc 000000000005512c  /system/lib64/libbinder.so (android::IPCThreadState::executeCommand(int)+1084)
    runtime.cc:655]   native: #116 pc 0000000000054c40  /system/lib64/libbinder.so (android::IPCThreadState::getAndExecuteCommand()+156)
    runtime.cc:655]   native: #117 pc 00000000000554a0  /system/lib64/libbinder.so (android::IPCThreadState::joinThreadPool(bool)+80)
    runtime.cc:655]   native: #118 pc 000000000007b4a0  /system/lib64/libbinder.so (android::PoolThread::threadLoop()+24)
    runtime.cc:655]   native: #119 pc 00000000000154cc  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+260)
    runtime.cc:655]   native: #120 pc 00000000000a4490  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+144)
    runtime.cc:655]   native: #121 pc 0000000000014d90  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+412)
    runtime.cc:655]   native: #122 pc 00000000000da278  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
    runtime.cc:655]   native: #123 pc 000000000007a448  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
    runtime.cc:655]   at c.a.rbsn(Native method)
    runtime.cc:655]   at a.c.m(:-1)
    runtime.cc:655]   at w1.c.f(Native method)
    runtime.cc:655]   at e.c.<init>(unavailable:-1)
    runtime.cc:655]   at f.f.f(Native method)
    runtime.cc:655]   at b.c.a(Native method)
    runtime.cc:655]   at com.core.Cmd.exec(:-1)
    runtime.cc:655]   at java.lang.reflect.Method.invoke(Native method)
2023-06-02 11:23:55.640 16166-16190/org.waxmoon.ma.github A/github:agent.p: runtime.cc:655]   at com.hack.utils.RefUtils$MethodRef.invoke(RefUtils.java:99)
    runtime.cc:655]   at com.hack.opensdk.Cmd.exec(Cmd.java:52)
    runtime.cc:655]   at com.hack.agent.ProviderBase.call(ProviderBase.java:32)
    runtime.cc:655]   at android.content.ContentProvider.call(ContentProvider.java:2448)
    runtime.cc:655]   at android.content.ContentProvider$Transport.call(ContentProvider.java:517)
    runtime.cc:655]   at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:296)
    runtime.cc:655]   at android.os.Binder.execTransactInternal(Binder.java:1161)
    runtime.cc:655]   at android.os.Binder.execTransact(Binder.java:1130)
    runtime.cc:655] 
2023-06-02 11:23:55.640 16166-16190/org.waxmoon.ma.github A/github:agent.p: runtime.cc:663] JNI DETECTED ERROR IN APPLICATION: ToReflectedMethod received NULL jclass
    runtime.cc:663]     in call to ToReflectedMethod
    runtime.cc:663]     from long c.a.rbsn(android.os.Binder, android.os.Binder)
    
    --------- beginning of crash
2023-06-02 11:23:55.640 16166-16190/org.waxmoon.ma.github A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 16190 (Binder:16166_2), pid 16166 (github:agent.p0)
2023-06-02 11:23:56.394 15791-15791/org.waxmoon.ma.github I/ActivityThread: Removing dead content provider:android.content.ContentProviderProxy@cf9ae1c
2023-06-02 11:23:56.504 15791-15842/org.waxmoon.ma.github I/ActivityThread: Removing dead content provider:android.content.ContentProviderProxy@f03da25
2023-06-02 11:23:56.507 15791-16157/org.waxmoon.ma.github W/System.err: android.os.DeadObjectException
2023-06-02 11:23:56.507 15791-16157/org.waxmoon.ma.github W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
2023-06-02 11:23:56.507 15791-16157/org.waxmoon.ma.github W/System.err:     at android.os.BinderProxy.transact(BinderProxy.java:568)
2023-06-02 11:23:56.507 15791-16157/org.waxmoon.ma.github W/System.err:     at i.p$a$a.s0(Native Method)
2023-06-02 11:23:56.507 15791-16157/org.waxmoon.ma.github W/System.err:     at i.g.A0(Native Method)
2023-06-02 11:23:56.507 15791-16157/org.waxmoon.ma.github W/System.err:     at f.f.B(Native Method)
2023-06-02 11:23:56.507 15791-16157/org.waxmoon.ma.github W/System.err:     at i.g.V(Native Method)
2023-06-02 11:23:56.507 15791-16157/org.waxmoon.ma.github W/System.err:     at a.g.q(Unknown Source:4)
2023-06-02 11:23:56.507 15791-16157/org.waxmoon.ma.github W/System.err:     at com.core.Cmd.exec(Unknown Source:765)
2023-06-02 11:23:56.507 15791-16157/org.waxmoon.ma.github W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2023-06-02 11:23:56.507 15791-16157/org.waxmoon.ma.github W/System.err:     at com.hack.utils.RefUtils$MethodRef.invoke(RefUtils.java:99)
2023-06-02 11:23:56.507 15791-16157/org.waxmoon.ma.github W/System.err:     at com.hack.opensdk.Cmd.exec(Cmd.java:52)
2023-06-02 11:23:56.508 15791-16157/org.waxmoon.ma.github W/System.err:     at com.hack.opensdk.HackApi.installPackageFromHost(HackApi.java:48)
2023-06-02 11:23:56.508 15791-16157/org.waxmoon.ma.github W/System.err:     at org.waxmoon.ma.ApkEnv.lambda$installApkAndQuickStartFromTask$0$org-waxmoon-ma-ApkEnv(ApkEnv.java:75)
2023-06-02 11:23:56.508 15791-16157/org.waxmoon.ma.github W/System.err:     at org.waxmoon.ma.ApkEnv$$ExternalSyntheticLambda1.run(Unknown Source:6)
2023-06-02 11:23:56.508 15791-16157/org.waxmoon.ma.github W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2023-06-02 11:23:56.508 15791-16157/org.waxmoon.ma.github W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2023-06-02 11:23:56.508 15791-16157/org.waxmoon.ma.github W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2023-06-02 11:23:56.508 15791-16157/org.waxmoon.ma.github W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2023-06-02 11:23:56.508 15791-16157/org.waxmoon.ma.github W/System.err:     at java.lang.Thread.run(Thread.java:923)
2023-06-02 11:23:56.511 15791-16157/org.waxmoon.ma.github W/System.err: android.os.DeadObjectException
2023-06-02 11:23:56.511 15791-16157/org.waxmoon.ma.github W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
2023-06-02 11:23:56.512 15791-16157/org.waxmoon.ma.github W/System.err:     at android.os.BinderProxy.transact(BinderProxy.java:568)
2023-06-02 11:23:56.512 15791-16157/org.waxmoon.ma.github W/System.err:     at i.p$a$a.D(Native Method)
2023-06-02 11:23:56.512 15791-16157/org.waxmoon.ma.github W/System.err:     at i.g.V(Native Method)
2023-06-02 11:23:56.512 15791-16157/org.waxmoon.ma.github W/System.err:     at a.g.q(Unknown Source:4)
2023-06-02 11:23:56.512 15791-16157/org.waxmoon.ma.github W/System.err:     at com.core.Cmd.exec(Unknown Source:765)
2023-06-02 11:23:56.512 15791-16157/org.waxmoon.ma.github W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2023-06-02 11:23:56.512 15791-16157/org.waxmoon.ma.github W/System.err:     at com.hack.utils.RefUtils$MethodRef.invoke(RefUtils.java:99)
2023-06-02 11:23:56.512 15791-16157/org.waxmoon.ma.github W/System.err:     at com.hack.opensdk.Cmd.exec(Cmd.java:52)
2023-06-02 11:23:56.512 15791-16157/org.waxmoon.ma.github W/System.err:     at com.hack.opensdk.HackApi.installPackageFromHost(HackApi.java:48)
2023-06-02 11:23:56.512 15791-16157/org.waxmoon.ma.github W/System.err:     at org.waxmoon.ma.ApkEnv.lambda$installApkAndQuickStartFromTask$0$org-waxmoon-ma-ApkEnv(ApkEnv.java:75)
2023-06-02 11:23:56.512 15791-16157/org.waxmoon.ma.github W/System.err:     at org.waxmoon.ma.ApkEnv$$ExternalSyntheticLambda1.run(Unknown Source:6)
2023-06-02 11:23:56.512 15791-16157/org.waxmoon.ma.github W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2023-06-02 11:23:56.512 15791-16157/org.waxmoon.ma.github W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2023-06-02 11:23:56.512 15791-16157/org.waxmoon.ma.github W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2023-06-02 11:23:56.512 15791-16157/org.waxmoon.ma.github W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2023-06-02 11:23:56.512 15791-16157/org.waxmoon.ma.github W/System.err:     at java.lang.Thread.run(Thread.java:923)
2023-06-02 11:23:56.513 15791-16157/org.waxmoon.ma.github D/Cmd: end exec 10 -1
2023-06-02 11:23:56.513 15791-16157/org.waxmoon.ma.github D/ApkEnv: installApkAndQuickStartFromTask absPath/data/user/0/org.waxmoon.ma.github/files/.plugin/direct/target.apk
2023-06-02 11:23:56.513 15791-16157/org.waxmoon.ma.github D/ApkEnv: installApkAndQuickStartFromTask ret-1
2023-06-02 11:23:56.513 15791-16157/org.waxmoon.ma.github D/ApkEnv: installApkIfNeeded pkg@com.example.android.codelab.animation success
2023-06-02 11:23:56.514 15791-16157/org.waxmoon.ma.github D/ApkEnv: startTargetApp begin

**Comment by WaxMoon** [comment]
plz update opensdk git module and try again
